export const favWorksArray = [
  {
    id: 9,
    name: "SkelPro",
    desc: "💀  SkelPro (Skeleton Project) simplifies project scaffolding by storing templates in JSON and crafting the perfect skeleton for your next big idea.",
    status: "New",
    site: "https://npmjs.com/package/skelpro",
    github: "https://github.com/SkelPro/skelpro",
    tools: ["typescript", "json", "npm"],
  },
  {
    id: 7,
    name: "Primary-energy-consumption Public",
    desc: "This project analyzes global primary energy consumption trends for various countries and regions. It includes data processing, visualization, statistical analysis, and machine learning to make predictions about future energy consumption.",
    status: "Done",
    github: "https://github.com/Sydney205/Primary-energy-consumption",
    tools: ["pandas", "matplotlib", "scikit-learn"],
  },
  {
    id: 8,
    name: "Translang",
    desc: "Translang: A translation web application adept at deciphering meaning in various linguistic contexts, developed using htmx and hono. 🌐🔍",
    status: "Live",
    site: "https://translang-xi.vercel.app",
    github: "https://github.com/Sydney205/Translang",
    tools: ["honojs", "htmx", "nodejs"],
  },
  {
    id: 6,
    name: "Tico",
    desc: "An awesome 1 v 1 multiplayer board gaming platform where users can play variety of boards games such as Tic-Tac-Toe, Chess and so on. It includes features like mulplaying and real-time chatting system.",
    status: "Upcoming",
    site: "https://tico-production.up.railway.app",
    github: "https://github.com/Sydney205/Tico",
    tools: ["nodejs", "socket.io", "tailwindcss"],
  },
];

export const workArrays = [
  {
    id: 9,
    name: "SkelPro",
    desc: "💀  SkelPro simplifies project scaffolding by storing templates in JSON and crafting the perfect skeleton for your next big idea.",
    status: "New",
    site: "https://npmjs.com/package/skelpro",
    github: "https://github.com/SkelPro/skelpro",
    tools: ["node", "typescript", "npm"],
  },
  {
    id: 8,
    name: "Translang",
    desc: "Translang: A translation web application adept at deciphering meaning in various linguistic contexts, developed using htmx and hono. 🌐🔍",
    status: "Live",
    site: "https://translang-xi.vercel.app",
    github: "https://github.com/Sydney205/Translang",
    tools: ["honojs", "htmx", "nodejs"],
  },
  {
    id: 7,
    name: "Primary-energy-consumption Public",
    desc: "This project analyzes global primary energy consumption trends for various countries and regions. It includes data processing, visualization, statistical analysis, and machine learning to make predictions about future energy consumption.",
    status: "Done",
    github: "https://github.com/Sydney205/Primary-energy-consumption",
    tools: ["pandas", "matplotlib", "scikit-learn"],
  },
  {
    id: 6,
    name: "Tico",
    desc: "An awesome 1 v 1 multiplayer board gaming platform where users can play variety of boards games such as Tic-Tac-Toe, Chess and so on. It includes features like mulplaying and real-time chatting system.",
    status: "Upcoming",
    site: "https://tico-production.up.railway.app",
    github: "https://github.com/Sydney205/Tico",
    tools: ["nodejs", "socket.io", "tailwindcss"],
  },
  {
    id: 5,
    name: "Maven Toys Dashboard",
    desc: "My first Tableau project: Maven Toys Dashboard (fictional mexico toys store) showcases the sales and profit analysis of products and their categories, store sales and profit.",
    status: "Live",
    site: "https://public.tableau.com/views/MavenToysDashboard_17306471825520/Dashboard?:language=en-US&publish=yes&:sid=&:redirect=auth&:display_count=n&:origin=viz_share_link",
    tools: ["tableau", "csv"],
  },
  {
    id: 10,
    name: "Super Store Analysis",
    desc: "📊 A project analyzing superstore data using Excel. Includes dashboards and pivot tables to show sales, profits, shipping, and returns. Easy to understand and useful for improving business decisions",
    status: "Done",
    github: "https://github.com/Sydney205/Super-store",
    tools: ["excel", "pivot-tables", "formulas"],
  },
  {
    id: 4,
    name: "Library Book Tracker",
    desc: "A simple SQL-based system to manage library data, including books, members, and borrow records. It demonstrates basic SQL operations such as creating tables, inserting data, and querying or updating records.",
    status: "Done",
    github: "https://github.com/Sydney205/Library-Book-Tracker",
    tools: ["sql"],
  },
  {
    id: 3,
    name: "Typeglide",
    desc: "Typeglide is a npm package that creates typing effect on console. Typeglide adds a dynamic touch by simulating a gradual appearance of text as if it's being typed.",
    status: "Published",
    site: "https://www.npmjs.com/package/typeglide",
    github: "https://github.com/Sydney205/typeglide",
    tools: ["nodejs", "typescript", "npm"],
  },
  {
    id: 1,
    name: "DashLink",
    desc: "📎 A simple and efficient URL shortener that transforms long URLs into compact, shareable links. Features include custom aliases and easy integration for streamlined link management.",
    status: "Down",
    github: "https://github.com/Sydney205/DashLink",
    tools: ["flask", "sql-alchemy", "python"],
  },
  {
    id: 11,
    name: "Wall Management",
    desc: "A Building and Branding Company that is thrilled to lead a complex initiatives.",
    status: "Live",
    site: "https://wall-management.vercel.app/",
    tools: ["Frontend", "React", "EmailJS"],
  },
  {
    id: 10,
    name: "Rust tictactoe AI",
    desc: "My attempt to create a tic-tac-toe game with Rust that has AI difficulty levels.",
    status: "Done",
    github: "https://github.com/Sydney205/Rust",
    tools: ["rust", "cargo"],
  },
  {
    id: 2,
    name: "Tonelog",
    desc: "Tonelog is a lightweight color logging package for Nodejs that Beautifully add colors and background colors log messages 🌈, Display current timestamp of log message 🕒, and Supports log levels (success, info, warning, error) 📊.",
    status: "Published",
    site: "https://www.npmjs.com/package/tonelog",
    github: "https://github.com/Sydney205/tonelog",
    tools: ["nodejs", "typescript", "npm"],
  },
];


// The HEX code #171b23 converts to the following RGB value:

// RGB(23, 27, 35). 🎨
